# Nome do Workflow, aparece na "Actions"
name: Pipeline CI/CD
# Define quando o pipeline vai ser ativado/disparado
on: 
  push:
    branches:
      - main
    paths: # Só dispara se arquivos nessa pasta mudarem
      - "src/**" # só mudanças no código fonte
      - ".github/workflows/**" # mudanças nos próprios pipelines
  workflow_dispatch: # habilita o botão "Run Workflow" no Github Actions
jobs:
  # Primeiro job: Build
  build:
    runs-on: ubuntu-latest #Imagem da maquina usada no CI
    
    steps:
      - name: checkout do código
        uses: actions/checkout@v6

      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: package-lock.json
          
      - name: Instalação das depêndencias
        run: npm install
        
      - name: Rodar o build
        run: npm run build

  # Secondo job
  tests:
    runs-on: ubuntu-latest #Imagem da maquina usada no CI
    needs: build

    steps:
      - name: checkout do código
        uses: actions/checkout@v6

      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Instalação das depêndencias
        run: npm install
        
      - name: Rodar lint
        run: npm run lint

      - name: Verificar formatação
        run: npm run format

      - name: Rodar testes
        run: npm run test

